# streamlit_app.py
# ---
# "Beta Hunt" – classroom leaderboard app for an MBA/Finance exercise
# Students submit three stocks: (i) beta near 0, (ii) beta near 1, (iii) highest beta.
# They enter the betas and upload proof screenshots. A real-time leaderboard ranks results.
#
# Persistence uses Supabase (Postgres + Storage). Configure via Streamlit secrets.
# If you prefer Google Sheets instead, see the README section at the bottom of this file.
#
# ------------------------------
# SETUP INSTRUCTIONS (short)
# 1) Create a free Supabase project → copy the Project URL and anon key into st.secrets:
#    [supabase]
url = "https://osbicvjsiptksuqkdwyt.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zYmljdmpzaXB0a3N1cWtkd3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMzExOTIsImV4cCI6MjA3NDkwNzE5Mn0.ys3Fba-I8RsU9oSr6ZfVjIj2BE3OPJ4CjgbfGdXt4o4"
bucket = "screenshots"   # create a public bucket with this name in Supabase Storage
table = "submissions"     # create a table with the schema below
admin_passphrase = "changeme"  # optional, for admin-only tools
#
# 2) In Supabase SQL editor, create the table:
#    CREATE TABLE IF NOT EXISTS public.submissions (
#      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
#      team TEXT NOT NULL,
#      student_name TEXT,
#      email TEXT,
#      stock0 TEXT,      beta0 DOUBLE PRECISION,
#      stock1 TEXT,      beta1 DOUBLE PRECISION,
#      stock_hi TEXT,    beta_hi DOUBLE PRECISION,
#      shot0_url TEXT, shot1_url TEXT, shothi_url TEXT,
#      notes TEXT
#    );
#    -- Recommended: one active row per team (latest wins). You can also add a unique constraint on (team, created_at) if you prefer historical tracking.
#
# 3) In Storage, create a public bucket named "screenshots".
#
# 4) Deploy this file to Streamlit Community Cloud.
# ------------------------------

Script execution error
File "/mount/src/testmgjg/test.py", line 50
  st.rerun()
  ^
IndentationError: expected an indented block after 'try' statement on line 49
